language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.0.10
  - SYMFONY_VERSION=origin/2.0

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install

notifications:
  email:
    - kristian@netvlies.nl